# Generated by Django 4.1.13 on 2024-02-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='usuario',
        ),
    ]
