# Generated by Django 4.1.13 on 2024-02-10 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('precio_desbloqueo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_minuto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Patinetes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('coste_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('patinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patinetes.patinete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patinetes.usuario')),
            ],
            options={
                'verbose_name_plural': 'Alquileres',
            },
        ),
    ]
