# Generated by Django 4.1.13 on 2024-02-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patinetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='debito',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
