# Generated by Django 4.1.13 on 2024-02-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patinetes', '0002_alter_usuario_debito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='debito',
            field=models.IntegerField(default=0),
        ),
    ]
