# Generated by Django 4.1.13 on 2024-02-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patinetes', '0003_alter_usuario_debito'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='temporal', max_length=128),
        ),
    ]
